version: "3.7"
services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      - app-network
    command: sh -c './wait-for.sh mongo:27017 -- yarn dev:start'
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
